#!/bin/bash
set -e
while [ -n "${1}" ]; do
    INFILE="${1}"
    date=$(exiftool -d %Y%m%d-%H%M%S -p '$CreateDate' "$INFILE")
    OUTFILE="${date}.jpg"

    if [ "${date}" == "" ]; then
	    echo "${INFILE} unmodified (couldn't read exif data)"
	elif [ "${OUTFILE}" == "${INFILE}" ]; then
	    echo "${INFILE} unmodified (file name already matches exif data)"
    else
        i=1
        while [ -e "${OUTFILE}" ]; do
            OUTFILE="${date}-${i}.jpg"
            let i++
        done

        echo "Rename ${INFILE} to ${OUTFILE}"
        mv "${INFILE}" "${OUTFILE}"
    fi

    shift
done

