#!/bin/bash
set -e
parse_switches=true
simulate=false

# void run_command(string command, bool simulate)
run_command()
{
    if $2; then
        echo "${1}"
    else
        echo "$(${1})"
    fi
}

while [ -n "${1}" ]; do
    if ${parse_switches}; then
        if [ "${1:0:1}" == "-" ]; then
            if [ "${1}" == "--" ]; then
                parse_switches=false
            elif [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
                echo "Usage: ${0} [OPTION]... [FILE]..."
                echo "Rename JPEG files based on their EXIF data."
                echo
                echo "-h, --help      This help message"
                echo "-s, --simulate  Simulate a run, only print what would be done"
                echo
                exit
            elif [ "${1}" == "-s" ] || [ "${1}" == "--simulate" ]; then
                echo "Simulation mode on"
                simulate=true
            else
                echo "Unrecognized option: ${1}"
                exit
            fi
            shift
            continue
        else
            parse_switches=false
        fi
    fi

    INFILE="${1}"
    date=$(exiftool -d %Y%m%d-%H%M%S -p '$CreateDate' "$INFILE")
    OUTFILE="${date}.jpg"

    if [ "${date}" == "" ]; then
	    echo "${INFILE} unmodified (couldn't read exif data)"
	elif [ "${OUTFILE}" == "${INFILE}" ]; then
	    echo "${INFILE} unmodified (file name already matches exif data)"
    else
        i=1
        while [ -e "${OUTFILE}" ]; do
            OUTFILE="${date}-${i}.jpg"
            let i++
        done

        echo "Rename ${INFILE} to ${OUTFILE}"
        run_command "mv ${INFILE} ${OUTFILE}" ${simulate}
    fi

    shift
done

