#!/bin/bash
set -e
while [ -n "${1}" ]; do
    INFILE="${1}"
    declare -i width=1280

    date=$(exiftool -d %Y%m%d_%H%M%S -p '$CreateDate' "$INFILE")

    jpegtopnm "${INFILE}" | pnmscale -width=${width} | \
	pnmtojpeg --quality=80 --optimize --progressive >"${date}.jpg"

    shift
done
